config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get  '/add',  to: 'products#new'
  post '/add',  to: 'products#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :products

end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :warehouses, dependent: :destroy

  attr_accessor :remember_token
	before_save { email.downcase! }

  validates :name,  presence: true, length: { maximum: 50 }

  #disallow double dots in email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy


  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @products = @user.products.paginate(page: params[:page])
    @warehouses = @user.warehouses.paginate(page: params[:page])

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Warehouse!"
      redirect_back_or @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 60 %>

  <div>
	  <%= link_to user.name, user %>

  	<% if current_user?(user) %>
  	<span class='gentle'>(You)</span>
  	<% end %>
	</div>

  <div>
  	<%= user.email %>
  </div>

  <div class="warning">
  <% if current_user.admin? && !current_user?(user) %>
    Admin options:
    <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
  <% end %>
	</div>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-3">
    <section class="user_info">
    	<%= gravatar_for @user %>
      <h1>
        <%= @user.name %>
      </h1>
      <div>
      	<%= @user.email %>
      </div>

      <div>
      	<%= pluralize(current_user.products.count, "product") %>
      </div>

    </section>
  </aside>
  <div class="col-md-9">
    <% if @user.products.any? %>
      <h3>Products (<%= @user.products.count %>)</h3>
    <% end %>
    <%= link_to "New product", add_url, class: "btn btn-lg btn-primary" %>
    <% if @user.products.any? %>
      <table class="table table-hover table-striped">
      	<thead>
		      <tr class="centered">
		      	<th>ID</th>
		        <th>Name</th>
		        <th>Description</th>
		        <th>Price</th>
		        <th>Quantity</th>
		        <th>Region</th>
		        <th>Edit</th>
		        <th>Delete</th>
		      </tr>
      	</thead>
      	<tbody>
      		<%= render @products %>
      	</tbody>
      </table>
    <% end %>
  </div>
  
  <div class="col-md-9">
    <% if @user.warehouses.any? %>
      <h3>Warehouses (<%= @user.warehouses.count %>)</h3>
    <% end %>
    <%= link_to "New warehouse", add_url, class: "btn btn-lg btn-primary" %>
    <% if @user.warehouses.any? %>
      <table class="table table-hover table-striped">
        <thead>
          <tr class="centered">
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Address</th>
            <th>Manager </th>
            <th>Manager Email</th>
            <th>Manager Phone Number</th>
            <th>Region</th>
          </tr>
        </thead>
        <tbody>
          <%= render @warehouses %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>