config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get  '/add',  to: 'products#new'
  post '/add',  to: 'products#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :products

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 140 }
  validates :description, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :region, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
	def index
	  @products = Product.paginate(page: params[:page])
	end

	def new
		@product = Product.new
	end

	def show
	  @product = Product.find(params[:id])
	  @user = User.find(product.user_id)
	end

	def create
		@product = current_user.products.build(product_params)
		@user = User.find(@product.user_id)
		if @product.save
		  flash[:success] = "Product added!"
		  redirect_back_or @user
		else
		  render 'static_pages/home'
		end
	end

	def destroy
		product = Product.find(params[:id])
		product.destroy
		flash[:success] = "Product deleted"
		redirect_back_or User.find(product.user_id)
	end

	def edit
	  @product = Product.find(params[:id])
	end

	def update
	  @product = Product.find(params[:id])
	  @user = User.find(@product.user_id)
	  if @product.update_attributes(product_params)
	    flash[:success] = "Product updated"
	    redirect_back_or @user
	  else
	    render 'edit'
	  end
	end
	private

		def product_params
		  params.require(:product).permit(:name, :description, :quantity,
		                               :price, :region)
		end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_area :description, size: "24x6", class: 'form-control' %>

  <%= f.label :price %>
  <%= number_field(:product, :price, in: 0.0..20.0, step: 0.01, class: 'form-control') %>

  <%= f.label :quantity %>
  <%= number_field(:product, :quantity, in: 0..99, step: 1, class: 'form-control') %>

  <%= f.label :region %>
  <%= f.number_field :region, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/products/_product.html.erb
<tr>
	<td ><%= product.id %></td>
	<td><%= product.name %></td>
	<td><%= product.description %></td>
	<td>$<%= product.price.round(2) %></td>
	<td><%= product.quantity %></td>
	<td><%= product.region %></td>
	<td><%= link_to "edit", edit_product_path(product) %>
	<td><%= link_to "delete", product, method: :delete %>
</td>
</tr>
 